config/routes.rb
Rails.application.routes.draw do
  resources :pasarelas
  resources :empresas do
    resources :usuarios
    resources :empresa_pasarelas
  end
  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => "pages#index"
end

app/models/pasarela.rb
# == Schema Information
#
# Table name: pasarelas
#
#  id           :integer          not null, primary key
#  eliminado    :boolean
#  estado       :boolean
#  nombre       :string(255)
#  url_servicio :string(255)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Pasarela < ApplicationRecord
     ## Scope para el index controlador
     scope :activas, -> { where(eliminado: false)}
     ## Scope para validar el estado de una pasarela
     scope :activa, -> { where(eliminado: false, estado: true)}
     
     def self.search_by(search_terms)
          where("LOWER(nombre) LIKE :search_term", search_term:"%#{search_terms.downcase}%")
     end

     def name
          self.nombre
     end
end

app/controllers/pasarelas_controller.rb
class PasarelasController < ApplicationController
  load_and_authorize_resource
  check_authorization
  before_action :set_pasarela, only: [:show, :edit, :update, :destroy]

  # GET /pasarelas
  # GET /pasarelas.json
  def index
    @pasarelas = Pasarela.activas.paginate(page: params[:page], per_page: 5)
    if params[:search].present? 
      @search_terms = params[:search]
      @pasarelas = @pasarelas.search_by(@search_terms)
    end
  end

  # GET /pasarelas/1
  # GET /pasarelas/1.json
  def show
  end

  # GET /pasarelas/new
  def new
    @pasarela = Pasarela.new
  end

  # GET /pasarelas/1/edit
  def edit
  end

  # POST /pasarelas
  # POST /pasarelas.json
  def create
    @pasarela = Pasarela.new(pasarela_params)
    @pasarela.estado = true
    @pasarela.eliminado = false
    respond_to do |format|
      if @pasarela.save
        format.html { redirect_to @pasarela, notice: 'Pasarela was successfully created.' }
        format.json { render :show, status: :created, location: @pasarela }
      else
        format.html { render :new }
        format.json { render json: @pasarela.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pasarelas/1
  # PATCH/PUT /pasarelas/1.json
  def update
    respond_to do |format|
      if @pasarela.update(pasarela_params)
        format.html { redirect_to @pasarela, notice: 'Pasarela was successfully updated.' }
        format.json { render :show, status: :ok, location: @pasarela }
      else
        format.html { render :edit }
        format.json { render json: @pasarela.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pasarelas/1
  # DELETE /pasarelas/1.json
  def destroy
    @pasarela.destroy
    respond_to do |format|
      format.html { redirect_to pasarelas_url, notice: 'Pasarela was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pasarela
      @pasarela = Pasarela.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pasarela_params
      params.require(:pasarela).permit(:nombre, :url_servicio, :estado, :eliminado)
    end
end

app/helpers/pasarelas_helper.rb
module PasarelasHelper
end

app/views/pasarelas/_form.html.erb
<%= simple_form_for(@pasarela) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :nombre %>
    <%= f.input :url_servicio %>
    <%= f.input :estado %>
  </div>

  <div class="form-actions text-center">
    <% if @pasarela.new_record? %>
        <%= f.button :submit, class:"btn btn-lg btn-success", :value => "Nueva pasarela" %>
    <% else %>
        <%= f.button :submit, class:"btn btn-lg btn-primary", :value => "Editar pasarela" %>
    <% end %>
  </div>
<% end %>

app/views/pasarelas/edit.html.erb
<h1>Editing Pasarela</h1>

<%= render 'form', pasarela: @pasarela %>

<%= link_to 'Regresar', pasarelas_path, class:"btn btn-lg btn-secondary" %>
<%= link_to 'Mostrar', @pasarela,  class:"btn btn-lg btn-info float-right" %> 

app/views/pasarelas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pasarelas</h1>

<%= form_for "", url: pasarelas_path, role: "search" , method: :get do  %>
  <%= text_field_tag :search, @search, placeholder: "Buscar ..." %>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pasarelas.each do |pasarela| %>
      <tr>
        <td><%= pasarela.nombre %></td>
        <td><%= estado_html(pasarela.estado) %></td>
        <td><%= link_to 'Mostar', pasarela, class:"btn btn-info"%></td>
        <td><%= link_to 'Editar', edit_pasarela_path(pasarela), class:"btn btn-warning" %></td>
        <td><%= link_to 'Eliminar', pasarela, method: :delete, class:"btn btn-danger", data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @collection, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
<br>

<%= link_to 'Nueva Pasarela', new_pasarela_path, class:"btn btn-lg btn-success" %>

app/views/pasarelas/new.html.erb
<h1>New Pasarela</h1>

<%= render 'form', pasarela: @pasarela %>

<%= link_to 'Regresar', pasarelas_path, class:"btn btn-lg btn-secondary" %>

app/views/pasarelas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @pasarela.nombre %>
</p>

<p>
  <strong>Url servicio:</strong>
  <%= @pasarela.url_servicio %>
</p>

<p>
  <strong>Estado:</strong>
  <%= estado_html(@pasarela.estado) %>
</p>



<%= link_to 'Regresar', pasarelas_path, class:"btn btn-lg btn-secondary" %>
<%= link_to 'Editar', edit_pasarela_path(@pasarela), class:"btn btn-lg btn-warning float-right" %> 