config/routes.rb
Rails.application.routes.draw do
  resources :pasarelas
  resources :empresas do
    resources :usuarios
    resources :empresa_pasarelas
  end
  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => "pages#index"
end

app/models/empresa_pasarela.rb
# == Schema Information
#
# Table name: empresa_pasarelas
#
#  id          :integer          not null, primary key
#  estado      :boolean
#  llave       :string(255)
#  merchant    :string(255)
#  username    :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  empresa_id  :integer          not null
#  pasarela_id :integer          not null
#  terminal_id :string(255)
#
# Indexes
#
#  i_emp_pas_pas_id                (pasarela_id)
#  i_empresa_pasarelas_empresa_id  (empresa_id)
#
# Foreign Keys
#
#  fk_rails_...  (empresa_id => empresas.id)
#  fk_rails_...  (pasarela_id => pasarelas.id)
#
class EmpresaPasarela < ApplicationRecord
  belongs_to :empresa
  belongs_to :pasarela
  scope :activas, -> { where(estado: true)}
  
end

app/controllers/empresa_pasarelas_controller.rb
class EmpresaPasarelasController < ApplicationController
  load_and_authorize_resource :empresa
  check_authorization
  before_action :authenticate_user!
  before_action :set_empresa
  before_action :set_empresa_pasarela, only: [:show, :edit, :update, :destroy]

  # GET /empresa_pasarelas
  # GET /empresa_pasarelas.json
  def index
    @empresa_pasarelas = @empresa.empresa_pasarelas.activas
  end

  # GET /empresa_pasarelas/1
  # GET /empresa_pasarelas/1.json
  def show
  end

  # GET /empresa_pasarelas/new
  def new
    @empresa_pasarela = EmpresaPasarela.new
  end

  # GET /empresa_pasarelas/1/edit
  def edit
  end

  # POST /empresa_pasarelas
  # POST /empresa_pasarelas.json
  def create
    @empresa_pasarela = EmpresaPasarela.new(empresa_pasarela_params)
    @empresa_pasarela.empresa_id = @empresa.id
    @empresa_pasarela.estado = true
    respond_to do |format|
      if @empresa_pasarela.save
        format.html { redirect_to empresa_empresa_pasarela_path(@empresa,@empresa_pasarela), notice: 'Empresa pasarela was successfully created.' }
        format.json { render :show, status: :created, location: @empresa_pasarela }
      else
        format.html { render :new }
        format.json { render json: @empresa_pasarela.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empresa_pasarelas/1
  # PATCH/PUT /empresa_pasarelas/1.json
  def update
    respond_to do |format|
      if @empresa_pasarela.update(empresa_pasarela_params)
        format.html { redirect_to empresa_empresa_pasarela_path(@empresa,@empresa_pasarela), notice: 'Empresa pasarela was successfully updated.' }
        format.json { render :show, status: :ok, location: @empresa_pasarela }
      else
        format.html { render :edit }
        format.json { render json: @empresa_pasarela.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empresa_pasarelas/1
  # DELETE /empresa_pasarelas/1.json
  def destroy
    @empresa_pasarela.destroy
    respond_to do |format|
      format.html { redirect_to empresa_pasarelas_path(@empresa), notice: 'Empresa pasarela was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empresa_pasarela
      @empresa_pasarela = EmpresaPasarela.find(params[:id])
    end

    def set_empresa
      @empresa = Empresa.find(params[:empresa_id])
    end

    # Only allow a list of trusted parameters through.
    def empresa_pasarela_params
      params.require(:empresa_pasarela).permit(:empresa_id, :pasarela_id, :estado, :username, :llave, :terminal_id, :merchant)
    end
end

app/helpers/empresa_pasarelas_helper.rb
module EmpresaPasarelasHelper
end

app/views/empresa_pasarelas/_form.html.erb
<%= simple_form_for([@empresa,@empresa_pasarela]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :pasarela,  collection: Pasarela.activa,  :input_html => {:onchange => "tipo_pasarela(this)"} %>
    <%= f.input :estado %>
    <%= f.input :username %>
    <%= f.input :llave %>
    <%= f.input :terminal_id %>
    <%= f.input :merchant %>
  </div>

  <div class="form-actions text-center">
    <% if @empresa_pasarela.new_record? %>
      <%= f.button :submit, class:"btn btn-lg btn-success", :value => "Agregar pasarela empresa" %>
    <% else %>
      <%= f.button :submit, class:"btn btn-lg btn-primary", :value => "Editar pasarela empresa" %>
    <% end %>
  </div>
<% end %>

app/views/empresa_pasarelas/edit.html.erb
<h1>Editar Empresa Pasarela</h1>

<%= render 'form', empresa_pasarela: @empresa_pasarela %>

<%= link_to 'Regresar', empresa_empresa_pasarelas_path(@empresa_pasarela.empresa_id), class: "btn btn-lg btn-secondary" %>
<%= link_to 'Mostrar',  empresa_empresa_pasarela_path(@empresa_pasarela.empresa_id, @empresa_pasarela.id), class: "btn btn-lg btn-info float-right" %> 

app/views/empresa_pasarelas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Empresa Pasarelas</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Pasarela</th>
      <th>Estado</th>
      <th>Username</th>
      <th>Llave</th>
      <th>Terminal</th>
      <th>Merchant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @empresa_pasarelas.each do |empresa_pasarela| %>
      <tr>
        <td><%= empresa_pasarela.pasarela.name %></td>
        <td><%= estado_html(empresa_pasarela.estado) %></td>
        <td><%= empresa_pasarela.username.truncate(20) %></td>
        <td><%= empresa_pasarela.llave.truncate(20) %></td>
        <td><%= empresa_pasarela.terminal_id.truncate(20) %></td>
        <td><%= empresa_pasarela.merchant %></td>
        <td><%= link_to 'Mostar', empresa_empresa_pasarela_path(@empresa.id, empresa_pasarela.id), class: "btn btn-lg btn-info" %></td>
        <td><%= link_to 'Editar', edit_empresa_empresa_pasarela_path(@empresa.id, empresa_pasarela.id), class: "btn btn-lg btn-warning" %></td>
        <td><%= link_to 'Eliminar', empresa_empresa_pasarela_path(@empresa.id, empresa_pasarela.id), class: "btn btn-lg btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Regresar', empresa_path(@empresa.id), class:"btn btn-lg btn-secondary" %>
<% if can? :create, @empresa_pasarela %>
<%= link_to 'Nueva Empresa Pasarela', new_empresa_empresa_pasarela_path(@empresa.id), class:"btn btn-lg btn-success float-right" %>
<% end %>

app/views/empresa_pasarelas/new.html.erb
<h1>Agregar Pasarela empresa</h1>

<%= render 'form', empresa_pasarela: @empresa_pasarela %>

<%= link_to 'Regresar', empresa_empresa_pasarelas_path(@empresa.id), class:"btn btn-lg btn-secondary" %>

app/views/empresa_pasarelas/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Pasarela:</strong>
  <%= @empresa_pasarela.pasarela.name %>
</p>

<p>
  <strong>Estado:</strong>
  <%= estado_html(@empresa_pasarela.estado) %>
</p>

<p>
  <strong>Username:</strong>
  <%= @empresa_pasarela.username %>
</p>

<p>
  <strong>Llave:</strong>
  <%= @empresa_pasarela.llave %>
</p>

<p>
  <strong>Terminal:</strong>
  <%= @empresa_pasarela.terminal_id %>
</p>

<p>
  <%if @empresa_pasarela.pasarela.name == "VISANET" %>
    <strong>Merchant:</strong>
    <%= @empresa_pasarela.merchant %>
  <% end %>
</p>

<%= link_to 'Regresar', empresa_empresa_pasarelas_path(@empresa_pasarela.empresa_id), class: "btn btn-lg btn-secondary" %>
<%= link_to 'Editar', edit_empresa_empresa_pasarela_path(@empresa_pasarela.empresa_id, @empresa_pasarela.id), class:"btn btn-lg btn-warning float-right" %>