config/routes.rb
Rails.application.routes.draw do
  resources :pasarelas
  resources :empresas do
    resources :usuarios
    resources :empresa_pasarelas
  end
  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => "pages#index"
end

app/models/empresa.rb
# == Schema Information
#
# Table name: empresas
#
#  id                  :integer          not null, primary key
#  direccion_comercial :string(255)
#  eliminado           :boolean
#  email               :string(255)
#  estado              :boolean
#  llave_api           :string(255)
#  nit                 :string(255)
#  nombre_comercial    :string(255)
#  razon_social        :string(255)
#  telefono            :string(255)
#  usuario             :string(255)
#  usuario_api         :string(255)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#
class Empresa < ApplicationRecord
     resourcify
     scope :activas, -> { where( eliminado: false)}

     validates :nit, presence: true, uniqueness: { case_sensitive: true }
     has_many :users
     has_many :usuarios
     has_many :empresa_pasarelas

     def self.search_by(search_terms)
          where("LOWER(nit) LIKE :search_term OR LOWER(nombre_comercial) LIKE :search_term OR LOWER(razon_social) LIKE :search_term", search_term:"%#{search_terms.downcase}%")
     end

     def name
          self.nombre_comercial
     end 

end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  load_and_authorize_resource
  check_authorization
  before_action :set_empresa, only: [:show, :edit, :update, :destroy]

  # GET /empresas
  # GET /empresas.json
  def index
    @empresas = Empresa.activas.order(created_at: :desc).paginate(page: params[:page], per_page: 5)
    if params[:search].present? 
      @search_terms = params[:search]
      @empresas = @empresas.search_by(@search_terms)
    end
  end

  # GET /empresas/1
  # GET /empresas/1.json
  def show
  end

  # GET /empresas/new
  def new
    @empresa = Empresa.new
  end

  # GET /empresas/1/edit
  def edit
  end

  # POST /empresas
  # POST /empresas.json
  def create
    @empresa = Empresa.new(empresa_params)
    @empresa.estado = true
    @empresa.eliminado = false
    respond_to do |format|
      if @empresa.save
        format.html { redirect_to @empresa, notice: 'Empresa was successfully created.' }
        format.json { render :show, status: :created, location: @empresa }
      else
        format.html { render :new }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empresas/1
  # PATCH/PUT /empresas/1.json
  def update
    respond_to do |format|
      if @empresa.update(empresa_params)
        if current_user.rol_admin?
          format.html { redirect_to @empresa, notice: 'Empresa was successfully updated.' }
          format.json { render :show, status: :ok, location: @empresa }
        elsif current_user.rol_empresa?
          format.html { redirect_to root_path, notice: 'Empresa was successfully destroyed.' }
          format.json { head :no_content }
        end
      else
        format.html { render :edit }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empresas/1
  # DELETE /empresas/1.json
  def destroy
    @empresa.update(eliminado: true)
    respond_to do |format|
      format.html { redirect_to empresas_url, notice: 'Empresa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empresa
      @empresa = Empresa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def empresa_params
      params.require(:empresa).permit(:nit, :razon_social, :nombre_comercial, :direccion_comercial, :email, :usuario, :telefono, :usuario_api, :llave_api, :estado, :eliminado)
    end
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/views/empresas/_form.html.erb
<%= simple_form_for(@empresa) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :nit %>
    <%= f.input :razon_social %>
    <%= f.input :nombre_comercial %>
    <%= f.input :direccion_comercial %>
    <%= f.input :email %>
    <%= f.input :telefono %>
    <%= f.input :usuario_api %>
    <%= f.input :llave_api %>
  </div>

  <div class="form-actions text-center">

    <% if @empresa.new_record? %>
        <%= f.button :submit, class:"btn btn-lg btn-success", :value => "Nueva empresa" %>
    <% else %>
        <%= f.button :submit, class:"btn btn-lg btn-primary", :value => "Editar empresa" %>
    <% end %>
  </div>
<% end %>

app/views/empresas/edit.html.erb
<h1>Modificar Empresa</h1>

<%= render 'form', empresa: @empresa %>
<% if current_user.rol_admin? %>
<%= link_to 'Mostar', @empresa, class: "btn btn-info" %> |
<% end %>
<%= link_to 'Regresar', empresas_path, class: "btn btn-lg btn-secondary" %>

app/views/empresas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Empresas</h1>
<%= form_for "", url: empresas_path, role: "search" , method: :get do  %>
  <%= text_field_tag :search, @search, placeholder: "Buscar ..." %>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nit</th>
      <th>Razon social</th>
      <th>Nombre comercial</th>
      <th>Direccion comercial</th>
      <th>Email</th>
      <th>Telefono</th>
      <th>Usuario api</th>
      <th>Llave api</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @empresas.each do |empresa| %>
      <tr>
        <td><%= empresa.nit %></td>
        <td><%= empresa.razon_social %></td>
        <td><%= empresa.nombre_comercial %></td>
        <td><%= empresa.direccion_comercial %></td>
        <td><%= empresa.email %></td>
        <td><%= empresa.telefono %></td>
        <td><%= empresa.usuario_api %></td>
        <td><%= empresa.llave_api %></td>
        <td><%= estado_html(empresa.estado) %></td>
        <td><%= link_to 'Mostrar', empresa, class: "btn btn-info" %></td>
        <td><%= link_to 'Editar', edit_empresa_path(empresa), class: "btn btn-warning" %></td>
        <td><%= link_to 'Eliminar', empresa, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @collection, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
<br>
<%= link_to 'Regresar', root_path, class:"btn btn-lg btn-secondary block" %>
<%= link_to 'Crear Empresa', new_empresa_path, class:"btn btn-lg btn-success block float-right" %>

app/views/empresas/new.html.erb
<h1>Crear Empresa</h1>

<%= render 'form', empresa: @empresa %>

<%= link_to 'Regresar', empresas_path, class: "btn btn-secondary" %>

app/views/empresas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nit:</strong>
  <%= @empresa.nit %>
</p>

<p>
  <strong>Razon social:</strong>
  <%= @empresa.razon_social %>
</p>

<p>
  <strong>Nombre comercial:</strong>
  <%= @empresa.nombre_comercial %>
</p>

<p>
  <strong>Direccion comercial:</strong>
  <%= @empresa.direccion_comercial %>
</p>

<p>
  <strong>Email:</strong>
  <%= @empresa.email %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @empresa.telefono %>
</p>

<p>
  <strong>Usuario api:</strong>
  <%= @empresa.usuario_api %>
</p>

<p>
  <strong>Llave api:</strong>
  <%= @empresa.llave_api %>
</p>

<p>
  <strong>Estado:</strong>
  <%= estado_html(@empresa.estado) %>
</p>


<p>
  <strong>Usuarios: </strong>
  <%= link_to "Usuarios", empresa_usuarios_path(@empresa), class:"btn btn-primary"%>
<p>

<p>
  <strong>Pasarelas: </strong>
  <%= link_to "pasarelas", empresa_empresa_pasarelas_path(@empresa), class:"btn btn-primary"%>
<p>


<%= link_to 'Regresar', empresas_path, class:"btn btn-lg btn-secondary" %>


<%= link_to 'Editar', edit_empresa_path(@empresa), class:"btn btn-lg btn-warning block float-right" %> 