config/routes.rb
Rails.application.routes.draw do
  resources :pasarelas
  resources :empresas do
    resources :usuarios
    resources :empresa_pasarelas
  end
  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => "pages#index"
end

app/views/layouts/_footer.html.erb
<footer class="py-5 bg-dark">
     <div class="container">
          <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
     </div>
    <!-- /.container -->
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
     <div class="container">
          <a class="navbar-brand" href="<%= root_path%>">Portal Pagos</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
               <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                         <a class="nav-link" href="<%= root_path %>">Home
                         <span class="sr-only">(current)</span>
                         </a>
                    </li>
                    <% if user_signed_in? %>
                         <% if current_user.rol_admin? %>
                              <li class="nav-item">
                                   <%= link_to "Empresas", empresas_path, class:"nav-link" %>
                              </li>
                              <li class="nav-item">
                                   <%= link_to "Pasarelas", pasarelas_path, class:"nav-link" %>
                              </li>
                         <% end %>
                         <% if current_user.rol_empresa? %>
                              <li class="nav-item">
                                   <%= link_to "Pasarelas", empresa_empresa_pasarelas_path(current_user.empresa_id), class:"nav-link" %>
                              </li>
                         <% end %>
                    <% end %>

                    <li class="nav-item">
                         <a class="nav-link" href="#">Contact</a>
                    </li>


                    <% if user_signed_in? %>
                         <li class="nav-item dropdown">
                              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                   <%= current_user.name%>
                              </a>
                              
                               <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                   <% if current_user.rol_empresa? %>
                                        <%= link_to 'Editar Empresa', edit_empresa_path(current_user.empresa_id), class:"dropdown-item" %>
                                        <%= link_to 'Usuarios', empresa_usuarios_path(current_user.empresa_id), class:"dropdown-item" %>
                                   <%end%>
                                   <%= link_to 'Edit Profile', edit_user_registration_path, class:"dropdown-item" %>
                                   <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class:"dropdown-item"  %>
                              </ul>
      
                         </li>
                    <% else %>
                         <li class="nav-link">
                              <%= link_to 'Ingreso', new_user_session_path, class:"nav-link" %>
                         </li>
                         <li class="nav-link">
                              <%# link_to 'Registro', new_user_registration_path, class:"nav-link" %>
                         </li>
                    <% end %>     
               </ul>
          </div>
     </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <head>
    <title>PagosInfile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% unless flash.empty? %>
      <script type="text/javascript">
        <% flash.each do |f| %>
          <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'success') %>
            toastr['<%= type %>']('<%= f[1] %>');
        <% end %>
      </script>
    <% end %>

    <header>
      <%= render 'layouts/navbar' %>
    </header>

    <main>
      <%= yield %>
    </main>

    <footer>
      <%= render 'layouts/footer' %>
    </footer>

  </body>
</html>